[tool.poetry]
name = "openbbsdkexplorer"
version = "0.1.0"
description = ""
authors = ["phbrgnomo <phbrcc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyterlab = "^4.0.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
